### ISSUE TITLE
example of PUT operation using py_canvas_api?

### ISSUE THREAD

**Issue by ashmanskas** [kajigga/py_canvas_api#1]
Thank you for creating this very useful API.  I love scripting these sorts of things in python.

I had no trouble using py_canvas_api for GET operations, for example extracting list of students in course, list of assignments for course, list of submissions for given assignment.

But I was unable to figure out how to make a PUT operation work using the API.  After a couple of hours of trying without success, I switched to simply using the 'curl' program to do the PUT that I needed:

curl https://canvas.foobar.edu/api/v1/courses/123/assignments/234/submissions/345 -X PUT \
  -F 'submission[posted_grade]=99' \
  -H 'Authorization: Bearer deadbeef'

If you have time, would you be willing to translate this (or similar) PUT operation into the proper syntax for your API and potentially add it to your list of "common requests" on the top-level README.rst ?

Many thanks,
Bill

**Comment by kajigga** [comment]
I am glad you find this module useful.  I don't have time to test it right now but a PUT operation should be done like this.

from canvas_api import Canvas
c = Canvas('canvas.foobar.edu', CANVAS_ACCESS_TOKEN="deadbeef")
data = {"submission":{"posted_grade":99}}
c.courses(123).assignments(234).submissions(345).put(data)
