### ISSUE TITLE
Documentation (i.e. README.rst) for SISImporter doesn't match actual method

### ISSUE THREAD

**Issue by clmcavaney** [kajigga/py_canvas_api#2]
The [README.rst](https://github.com/kajigga/py_canvas_api/blob/master/README.rst) mentions to call `SISImporter()` method with a parameter `CANVAS_API_TOKEN=` but the constructor doesn't name that parameter - see:
https://github.com/kajigga/py_canvas_api/blob/69bc40cd54c9c166a8533dd0ba7dcf6ebbc21198/py_canvas_api/sis_importer.py#L7

I'm wondering if the constructor should be changed to be consistent with the `Canvas` class or should the README.rst be modified?

**Comment by kajigga** [comment]
Good catch. I adjusted the documentation
